config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :restaurants, shallow: true do
    resource :reviews do
      resources :endorsements
    end
  end

  root to: "restaurants#index"

end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
  belongs_to :review
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  validates :name, length: {minimum: 3}, uniqueness: true
  has_many :reviews, dependent: :destroy
  belongs_to :user

  def build_review(attributes = {}, user)
    review = reviews.build(attributes)
    review.user = user
    review
  end

  def average_rating
      return 'N/A' if reviews.none?
      reviews.average(:rating)
    end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :user
  has_many :endorsements
  validates :rating, inclusion: (1..5)
  validates :user, uniqueness: { scope: :restaurant, message: "has reviewed this restaurant already" }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :restaurants
  has_many :reviews
  has_many :reviewed_restaurants, through: :reviews, source: :restaurant

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def has_reviewed?(restaurant)
    reviewed_restaurants.include? restaurant
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController

  def create
    @review = Review.find(params[:review_id])
    @review.endorsements.create
    redirect_to restaurants_path
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @current_user = current_user
    @restaurant = @current_user.restaurants.new(restaurant_params)
    if @restaurant.save
      redirect_to '/restaurants'
    else
      render 'new'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to '/restaurants'
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    flash[:notice] = 'Restaurant deleted successfully'
    redirect_to '/restaurants'
  end

  def restaurant_params
    params.require(:restaurant).permit(:name)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.build_review review_params, current_user
    if @review.save
      redirect_to restaurants_path
    else
      if @review.errors[:user]
        redirect_to restaurants_path, alert: "You have already reviewed this restaurant"
      else
        render :new
      end
    end
  end

  def review_params
    params.require(:review).permit(:thoughts, :rating)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_ommiauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_path
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def star_rating(rating)
    return rating unless rating.respond_to?(:round)
    remainder = (5-rating)
    '★' * rating.round + '☆' * remainder
  end
end

app/views/layouts/application.html.haml
%html
  %head
    %meta(charset="UTF-8")
    %title YelpClone
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

-if user_signed_in?
  = link_to "Sign out", destroy_user_session_path, method: :delete

-else
  = link_to "Sign in", new_user_session_path
  = link_to "Sign up", new_user_registration_path
  = link_to 'Sign in with Facebook', user_omniauth_authorize_path(:facebook)

%body
  = notice
  = alert
  = yield

app/views/restaurants/edit.html.haml
= form_for @restaurant do |f|
  = f.label :name
  = f.text_field :name
  = f.submit

app/views/restaurants/index.html.haml
- if @restaurants.any?
  - @restaurants.each do |restaurant|
    %h2= link_to restaurant.name, restaurant_path(restaurant)
    %h3 Average rating: #{star_rating(restaurant.average_rating.to_f)}
    %h4= link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant)
    %h4= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete
    %h4= link_to "Review #{restaurant.name}", new_restaurant_reviews_path(restaurant)

    %h4
      Reviews for
      = restaurant.name

      - if restaurant.reviews.any?
        %ul
          - restaurant.reviews.each do |review|
            %p= pluralize review.endorsements.count, 'endorsement'
            %li
              = review.thoughts
              %strong= review.rating
              \/5
      - else
        %p No reviews

- else
  %h1 No restaurants yet!


=link_to 'Add a restaurant', new_restaurant_path

app/views/restaurants/new.html.haml
-if @restaurant.errors.any?
  %section#errors
    %h2
      =pluralize @restaurant.errors.count, "error"
      prohibited this restaurant from being saved:
    %ul
    - @restaurant.errors.full_messages.each do |message|
      %li= message

=form_for @restaurant do |f|
  =f.label :name
  =f.text_field :name
  =f.submit

app/views/restaurants/show.html.haml
%h1
  = @restaurant.name
  = @restaurant.description
-if user_signed_in?
  %h3
    = link_to "Review #{@restaurant.name}", new_restaurant_review_path(@restaurant)

- if @restaurant.reviews.any?
  %ul
    - @restaurant.reviews.each do |rev|
      %li
        Review Thoughts:
        =rev.thoughts
        Review Rating
        %strong
          = rev.rating
          \/5
- else
  %p No reviews

app/views/reviews/new.html.haml
-if @review.errors.any?
  %section#errors
    %h2
      =pluralize @review.errors.count, "error"
      prohibited this review from being saved:
    %ul
    - @review.errors.full_messages.each do |message|
      %li= message

=form_for [@restaurant, @review] do |f|
  =f.label :thoughts
  =f.text_field :thoughts
  =f.label :rating
  =f.select :rating, (1..100)
  =f.submit 'Leave Review'